plugins { id 'com.android.application' }

def ciRun = System.getenv("GITHUB_RUN_NUMBER") ?: "1"
def ciCode = Integer.parseInt(ciRun)

android {
    namespace 'com.aplika.avraham'
    compileSdk 35

    defaultConfig {
        applicationId 'com.aplika.avraham'
        minSdk 26
        targetSdk 35
        versionCode ciCode
        versionName "1.0." + ciRun
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}
